language: rust
cache: cargo

rust:
  - stable
  - beta
  - nightly
  - 1.14.0
os:
 - linux
 - windows

script:
  - cargo build --verbose --features=fuzztarget
  - cargo build --verbose --features=rand
  - cargo test --verbose --features=rand
  - cargo test --verbose --features="rand serde"
  - cargo build --verbose
  - cargo test --verbose
  - cargo build --release
  - cargo test --release
  - cargo bench
  - if [ "$(rustup show | grep default | grep stable)" != "" ]; then cargo doc; fi
