[package]

name = "secp256k1"
version = "0.0.1"
authors = [ "Dawid Ciężarkiewicz <dpc@ucore.info>",
            "Andrew Poelstra <apoelstra@wpsoftware.net" ]

[lib]
name = "secp256k1"
path = "src/secp256k1.rs"

[dependencies.rust-crypto]
git = "https://github.com/DaGenix/rust-crypto.git"

